# permissions for end users to edit assumerolepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assumerolepolicy-editor-role
rules:
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - assumerolepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - assumerolepolicies/status
  verbs:
  - get
