# permissions for end users to view assumerolepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assumerolepolicy-viewer-role
rules:
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - assumerolepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - assumerolepolicies/status
  verbs:
  - get
