# permissions for end users to view policyattachments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyattachment-viewer-role
rules:
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - policyattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws-iam.redradrat.xyz
  resources:
  - policyattachments/status
  verbs:
  - get
